server:
  port: 18089
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.10.200:3306/changgou_order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 172.16.10.200
    port: 6379
  rabbitmq:
    host: 172.16.10.200
    username: guest
    password: guest
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
# 开启feign的熔断：默认是线程池隔离
feign:
  hystrix:
    enabled: true
# 如果开启了熔断，则默认是线程池隔离，会启用新的数据，需要将熔断策略换成信号量隔离，此时不会开启新的线程
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000000
          strategy: SEMAPHORE # 信号量 共享线程
#位置支付交换机和队列
mq:
  pay:
    queue:
      order: queue.order